### ISSUE TITLE
[inquiry] - is this repo still actively being maintained?

### ISSUE THREAD

**Issue by 7php** [humanmade/wp-redis-predis-client#7]
and is there any future plans?

**Comment by rmccue** [comment]
We're still maintaining this and using it in production. I believe that the plugin generally is [complete](https://engineering.hmn.md/how-we-work/philosophy/completion/) though, so don't think we have any particular plans.

**Comment by 7php** [comment]
thank you @rmccue .
Just out of curiosity, have you guys switched to Redis v6.0.1 or sticking to v5.x?

**Comment by rmccue** [comment]
We're using AWS Elasticache for Redis, which appears to be in 4.x engine mode on our stacks right now.
